apiVersion: apps/v1
kind: Deployment
metadata:
  name: expiration-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: expiration
  template:
    metadata:
      labels:
        app: expiration
    spec:
      containers:
        - name: expiration
          image: 29ff/ticketapp-expiration
          env:
            - name: NATS_CLUSTER_ID
              value: ticketapp
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NATS_URL
              value: http://nats-srv:4222
            - name: REDIS_HOST
              value: expiration-redis-srv
      imagePullSecrets:
        - name: docker-registry
